name: Deploy Model Service

on:
  push:
    branches: [main]
    paths:
      - "app/ml_service/**"
  pull_request:
    branches: [main]
    paths:
      - "app/ml_service/**"

jobs:

  review:
    name: Check Required Files
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify required files exist
        run: |
          required_files=("app.py" "Dockerfile" "requirements.txt")

          for file in "${required_files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "Missing required file: $file"
              exit 1
            else
              echo "Found $file"
            fi
          done


  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: review

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t my-app .


  deploy:
    name: Push to HuggingFace Space
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs
          git lfs install

      - name: Clone HuggingFace Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          HF_SPACE_NAME: ${{ secrets.HF_SPACE_NAME }}
        run: |
          git clone https://user:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$HF_SPACE_NAME space

      - name: Copy project files
        run: |
          rsync -av --exclude=".git" ./ space/

      - name: Commit and Push
        run: |
          cd space
          git config user.email "github-actions@github.com"
          git config user.name "github-actions"
          git add .
          git commit -m "Auto deploy from GitHub Actions"
          git push